### ISSUE TITLE
Is there a newer version of the mvnw script available?

### ISSUE THREAD

**Issue by DavidWhitlock** [JoyOfCodingPDX/JoyOfCoding#421]
I just noticed that I was able to run `mvnw` on a Windows machine without it running into a problem with `curl` like a student saw.  I wonder if we're using an old version of the `mvnw` script.

**Comment by DavidWhitlock** [comment]
It looks like there is also `mvnwDebug` script that can be added, too:

https://maven.apache.org/wrapper/maven-wrapper-plugin/usage.html

**Comment by DavidWhitlock** [comment]
See also #335.

**Comment by DavidWhitlock** [comment]
It looks like we're using the latest takari Maven Wrapper: https://mvnrepository.com/artifact/io.takari/maven-wrapper

The official Apache one still only works with Maven 4 and that still isn't available yet.

**Comment by kiwi-oss** [comment]
The official Apache wrapper works fine with Maven 3, see one of my Maven wrapper properties files:
```properties
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.1/maven-wrapper-3.1.1.jar
```

You just have to set it up as [described here](https://github.com/DavidWhitlock/PortlandStateJava/issues/335#issuecomment-1193090750).
